# Copyright (C) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Run fuzzy tests

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/fuzzy-testing.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/scripts/fuzzy_test.py"
      - "test/scripts/link_h5_dataset.py"
      - "CMakeLists.txt"
      - "conanfile.txt"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/fuzzy-testing.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/scripts/fuzzy_test.py"
      - "test/scripts/link_h5_dataset.py"
      - "CMakeLists.txt"
      - "conanfile.txt"

  schedule:
    # Run weekly
    - cron: '15 3 * * 0'

  workflow_dispatch:
    inputs:
      duration:
        description: 'Test duration in seconds'
        required: true
        default: '600'
        type: string

      resolution:
        description: 'Matrix resolution to use for testing'
        required: true
        default: '10000'
        type: string


# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-22.04-cxx-clang-15
      options: "--user=root"

    env:
      CONAN_HOME: '/root/.conan2'

    steps:
      - uses: actions/checkout@v3

      - name: Fix permissions
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Generate cache key
        id: cache-key
        run: |
          hash="${{ hashFiles('conanfile.txt', '.github/workflows/fuzzy-testing.yml') }}"

          echo "key=fuzzy-testing-$hash" >> $GITHUB_OUTPUT

      - name: Restore Conan cache
        id: cache-conan
        uses: actions/cache/restore@v3
        with:
          key: conan-${{ steps.cache-key.outputs.key }}
          path: ${{ env.CONAN_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source
          conan remove --confirm "*"

      - name: Install build dependencies
        run: |
          conan install .                             \
             --build=missing                          \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH"      \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH"      \
             -s build_type=Release                    \
             -s compiler.libcxx=libstdc++11           \
             -s compiler.cppstd=17                    \
             --output-folder=build

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Save Conan cache
        uses: actions/cache/save@v3
        if: steps.cache-conan.outputs.cache-hit != 'true'
        with:
          key: conan-${{ steps.cache-key.outputs.key }}
          path: ${{ env.CONAN_HOME }}

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release                   \
                -DCMAKE_PREFIX_PATH="$PWD/build"             \
                -DENABLE_DEVELOPER_MODE=ON                   \
                -DOPT_ENABLE_SANITIZER_ADDRESS=ON            \
                -DOPT_ENABLE_SANITIZER_LEAK=ON               \
                -DOPT_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON \
                -DOPT_ENABLE_CLANG_TIDY=OFF                  \
                -DHICTK_BUILD_TOOLS=ON                       \
                -DHICTK_BUILD_BENCHMARKS=OFF                 \
                -DHICTK_BUILD_EXAMPLES=OFF                   \
                -DHICTK_ENABLE_TESTING=OFF                   \
                -S .                                         \
                -B build

      - name: Build project
        run: cmake --build build -j $(nproc)

      - name: Upload hictk
        uses: actions/upload-artifact@v3
        with:
          name: hictk-tools-fuzzy-testing
          path: build/src/hictk/hictk
          if-no-files-found: error
          retention-days: 1

  run-tests:
    runs-on: ubuntu-latest
    needs: build-project
    container:
      image: ubuntu:22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - {
            url: 'https://www.dropbox.com/s/97fidisur8hflar/4DNFI9FVHJZQ.fixed.mcool?dl=1',
            sha256: '3b220810d7e9434fbebd00eb451e0ff7382b9b6fef88681aa3d6da9db84e818f',
            ref-url: 'https://www.dropbox.com/s/97fidisur8hflar/4DNFI9FVHJZQ.fixed.mcool?dl=1',
            ref-sha256: '3b220810d7e9434fbebd00eb451e0ff7382b9b6fef88681aa3d6da9db84e818f',
            balance: 'NONE'
          }
          - {
            url: 'https://www.dropbox.com/s/97fidisur8hflar/4DNFI9FVHJZQ.fixed.mcool?dl=1',
            sha256: '3b220810d7e9434fbebd00eb451e0ff7382b9b6fef88681aa3d6da9db84e818f',
            ref-url: 'https://www.dropbox.com/s/97fidisur8hflar/4DNFI9FVHJZQ.fixed.mcool?dl=1',
            ref-sha256: '3b220810d7e9434fbebd00eb451e0ff7382b9b6fef88681aa3d6da9db84e818f',
            balance: 'weight'
          }
          - {
            url: 'https://www.dropbox.com/s/gkzxt5ae82dvlrg/4DNFIPC7P27B.hic?dl=1',
            sha256: 'b1ba1c942693a5b6e494de7f8da097a1435598a9bb951219929b5a84cb2a6b42',
            ref-url: 'https://www.dropbox.com/s/97fidisur8hflar/4DNFI9FVHJZQ.fixed.mcool?dl=1',
            ref-sha256: '3b220810d7e9434fbebd00eb451e0ff7382b9b6fef88681aa3d6da9db84e818f',
            balance: 'NONE'
          }

    steps:
      - name: Install test dependencies
        run: |
          apt-get update
          apt-get install -y curl git python3-pip zstd
          pip install --no-cache-dir 'cooler>=0.9.2'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.after }}

      - name: Download test datasets
        run: |
          echo "${{ matrix.sha256 }}  test.matrix" > checksums.sha256
          echo "${{ matrix.ref-sha256 }}  reference.mcool" >> checksums.sha256

          curl -sL "${{ matrix.url }}" -o test.matrix &
          curl -sL "${{ matrix.ref-url }}" -o reference.mcool

          wait

          sha256sum -c checksums.sha256

      - name: Fix permissions
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Detect CI type
        id: ci-type
        run: |
          if git log --format=%B -n 1 ${{ github.event.after }} | grep -qF '[ci full]'; then
            echo "type=full" >> $GITHUB_OUTPUT
          else
            echo "type=short" >> $GITHUB_OUTPUT
          fi

      - name: Download hictk
        uses: actions/download-artifact@v3
        with:
          name: hictk-tools-fuzzy-testing

      - name: Prepare for test
        id: test-params
        env:
          PYTHONHASHSEED: 0
        run: |
          seed="$(python3 -c 'import random; print(random.randint(0, 2**32))')"

          duration=600
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            duration='${{ inputs.duration }}'
          elif [[ ${{ steps.ci-type.outputs.type }} == 'full' ]]; then
            duration=3600
          fi

          resolution=10000
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            resolution='${{ inputs.resolution }}'
          fi

          if cooler cp "test.matrix::/resolutions/$resolution" test.matrix.tmp; then
            mv test.matrix.tmp test.matrix
          fi

          2>&1 echo "Seed: ${seed}"
          2>&1 echo "Duration: ${duration}"
          2>&1 echo "Resolution: ${resolution}"

          echo "seed=$seed" >> $GITHUB_OUTPUT
          echo "duration=$duration" >> $GITHUB_OUTPUT
          echo "resolution=$resolution" >> $GITHUB_OUTPUT

      - name: Run test
        run: |
          chmod 750 hictk
          hictk="$(readlink -f ./hictk)"

          test/scripts/fuzzy_test.py \
            --path-to-hictk="$hictk" \
            --resolution '${{ steps.test-params.outputs.resolution }}' \
            --seed '${{ steps.test-params.outputs.seed }}' \
            --duration '${{ steps.test-params.outputs.duration }}' \
            --balance ${{ matrix.balance }} \
            test.matrix \
            reference.mcool

  fuzzy-testing-status-check:
    name: Status Check (fuzzy-testing)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-project
      - run-tests

    steps:
      - name: Collect job results
        if: |
          needs.build-project.result != 'success'        ||
          needs.run-tests.result != 'success'
        run: exit 1
